import os
from Bio import Entrez
from datetime import datetime

# --- 配置区 ---
EMAIL = "duanwenqiang1227@gmail.com" 
SEARCH_QUERY = '("Breast Neoplasms"[Mesh]) AND ("HR positive" OR "HR+") AND ("HER2 negative" OR "HER2-")'

def fetch_papers():
    Entrez.email = EMAIL
    # 目前设为 30 天，确保每次都能搜到点东西进行演示
    handle = Entrez.esearch(db="pubmed", term=SEARCH_QUERY, reldate=30, datetype="pdat")
    record = Entrez.read(handle)
    id_list = record["IdList"]
    if not id_list: return []
    handle = Entrez.efetch(db="pubmed", id=id_list, rettype="medline", retmode="xml")
    papers = Entrez.read(handle)
    return papers['PubmedArticle']

def format_to_md(article):
    medline = article['MedlineCitation']
    article_data = medline['Article']
    title = article_data['ArticleTitle']
    journal = article_data.get('Journal', {}).get('Title', 'Unknown')
    
    doi = ""
    for x in article['PubmedData']['ArticleIdList']:
        if x.attributes.get('IdType') == 'doi': doi = str(x)
    abstract_text = ""
    if 'Abstract' in article_data:
        abstract_text = "\n".join(article_data['Abstract']['AbstractText'])
    
    filename = f"Papers/{medline['PMID']}.md"
    content = f"""---
title: "{title}"
journal: "{journal}"
doi: "{doi}"
tags: #BC #HR+HER2- #AutoGenerated
date: {datetime.now().strftime('%Y-%m-%d')}
---
# {title}
**Journal**: {journal} | **DOI**: [{doi}](https://doi.org/{doi})
## Abstract
{abstract_text}
"""
    return filename, content, {"pmid": medline['PMID'], "title": title, "journal": journal, "date": datetime.now().strftime('%Y-%m-%d')}

def update_index(new_papers_info):
    index_file = "BC_Papers_Index.md"
    header = "# BC Papers Index\n\n| Date | Journal | Title | Link |\n| --- | --- | --- | --- |\n"
    
    # 如果索引文件已存在，读取旧内容
    existing_entries = []
    if os.path.exists(index_file):
        with open(index_file, "r", encoding="utf-8") as f:
            lines = f.readlines()
            # 跳过表头 4 行
            existing_entries = lines[4:]

    # 构造新条目
    new_entries = []
    for info in new_papers_info:
        line = f"| {info['date']} | {info['journal']} | {info['title']} | [[{info['pmid']}]] |\n"
        if line not in existing_entries: # 避免重复
            new_entries.append(line)

    # 写入文件 (新论文放在最上面)
    with open(index_file, "w", encoding="utf-8") as f:
        f.write(header)
        for line in new_entries:
            f.write(line)
        for line in existing_entries:
            f.write(line)

if __name__ == "__main__":
    if not os.path.exists("Papers"): os.makedirs("Papers")
    papers = fetch_papers()
    print(f"Found {len(papers)} papers.")
    
    new_papers_info = []
    for p in papers:
        result = format_to_md(p)
        if result:
            fname, text, info = result
            if not os.path.exists(fname):
                with open(fname, "w", encoding="utf-8") as f:
                    f.write(text)
                new_papers_info.append(info)
    
    if new_papers_info:
        update_index(new_papers_info)
        print(f"Updated index with {len(new_papers_info)} new papers.")
