name: PubMed Sync
on:
  schedule:
    - cron: '0 0 * * 1' 
  workflow_dispatch:   

jobs:
  run-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 显式声明需要写权限
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install biopython

      - name: Run Script
        run: python pubmed_to_obsidian.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Papers/
          # 检查是否有新文件，如果有才提交
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "New papers found"
            git push
          else
            echo "No changes found."
          fi
