name: PubMed Sync
on:
  schedule:
    - cron: '0 0 * * 1' 
  workflow_dispatch:   

jobs:
  run-sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 获取所有历史，防止冲突

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install biopython

      - name: Run Script
        run: python pubmed_to_obsidian.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Papers/
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "New papers found"
            git pull --rebase  # 先同步远程改动
            git push
          else
            echo "No changes found."
          fi
